services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: "gunicorn pricetracker.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - rabbitmq_server
  
  rabbitmq_server:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery_worker:
    build: ./app     
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq_server
      - db
    command: "celery -A pricetracker worker -l INFO "

  celery_beat:
    build: ./app     
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq_server
      - db
    command: "celery -A pricetracker beat -l INFO "

  db:
    image: postgres:15.1-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

  
volumes:
    postgres_data:
    rabbitmq_data: