# Generated by Django 4.1.3 on 2022-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_product_slug_product_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='imgs/'),
        ),
    ]
