# Generated by Django 4.1.3 on 2022-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_product_id_alter_product_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=512),
        ),
    ]
