# Generated by Django 4.1.3 on 2022-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(default='ASIN000', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
