# Generated by Django 4.1.4 on 2023-02-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_rename_asin_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.CharField(default='NA', max_length=40),
        ),
    ]
