# Generated by Django 4.1.3 on 2022-11-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(default='ASIN000', max_length=20, unique=True),
        ),
    ]
