# Generated by Django 4.1.3 on 2022-12-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_product_date_added_product_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='list_price',
        ),
    ]
