# Generated by Django 4.1.3 on 2022-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_product_list_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timestamp',
            new_name='added_at',
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
